package thewrestler.signaturemoves.upgrades;

public enum UpgradeType {
  DAMAGE,
  COST_REDUCTION,
  NUM_ATTACKS,
  MAGIC_NUMBER_INCREASE,
  DRAWBACK_REDUCTION,
  RETAIN,
  LOSE_EXHAUST,
  ALL_ENEMIES_1,
  ALL_ENEMIES_2,
  ALL_ENEMIES_3,
  SPECIAL_1,
  SPECIAL_2,
  SPECIAL_3
}
